### ISSUE TITLE
Icons are broken

### ISSUE THREAD

**Issue by quentin-abei** [danielcranney/profileme-dev#103]
Icons just appear as text "ICON" in markdown, result we don't get icons showing on profile , instead we get plain text 3ICON"

**Comment by quentin-abei** [comment]
well i hope he will fix it soon

**Comment by AntonioBerna** [comment]
> well i hope he will fix it soon

you'd better close this issue to avoid confusion with issue #97

**Comment by danielcranney** [comment]
Thanks for the heads up @AntonioBerna. This issue is now resolved.
