### ISSUE TITLE
Icons are not displayed in Profileme.dev and readme.md files

### ISSUE THREAD

**Issue by vzan2012** [danielcranney/profileme-dev#122]
Hello @danielcranney,

The skill set icons are not displayed and it takes longer time to load. 

![image](https://github.com/danielcranney/profileme-dev/assets/13725828/7b1e858e-ff39-4b11-b7c8-36e2f5648500)

**SVG Icons**
https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/nodejs-colored.svg
https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/express-colored.svg

**Comment by danielcranney** [comment]
This appears to have been a temporary issue and could not be re-created. 
Thanks for logging it.
