### ISSUE TITLE
Some icons are not displayed (Instagram, Discord)

### ISSUE THREAD

**Issue by Pyramond** [danielcranney/profileme-dev#129]
![profileMe1](https://github.com/danielcranney/profileme-dev/assets/83555414/b75bfc21-a511-4e79-9825-a4eb86ddc075)
![profileMe2](https://github.com/danielcranney/profileme-dev/assets/83555414/5d73c7ce-7ec0-4f23-9ff2-72c7f46a462d)

**Comment by danielcranney** [comment]
This appears to have been a temporary issue, and could not be replicated. 
Thank you for reporting this, I will now close this issue.
