### ISSUE TITLE
Certain Stats not being displayed due to an error in Vercel app - Environment variable to be defined

### ISSUE THREAD

**Issue by i01001** [danielcranney/profileme-dev#13]
![Screenshot from 2022-05-18 15-58-31](https://user-images.githubusercontent.com/88283950/169033618-f233a108-1a61-4872-aada-d8f1a4c5f22b.png)

Hello Daniel!

An issue with Vercel to do with environment variable. 

Appararently for all users.

Please have a look :)

**Comment by danielcranney** [comment]
Issue appears to have been temporary, and has resolved.
