### ISSUE TITLE
None of the icons are displayed 

### ISSUE THREAD

**Issue by VisionaryCodeX** [danielcranney/profileme-dev#130]
Icons for skills and socials were showing good yesterday but when i logined the next day i can't see any skills or socials icons 
![image](https://github.com/danielcranney/profileme-dev/assets/132255165/93eacb45-a669-4cde-9c72-47dc3b9a5f23)

**Comment by danielcranney** [comment]
This appears to have been a temporary issue, and could not be replicated. Thanks for reporting, but I will now close this issue.
