### ISSUE TITLE
Markdown render issues.

### ISSUE THREAD

**Issue by mamaoag** [danielcranney/profileme-dev#2]
I used your profileme.dev and really helpful in setting up a readme file for my github profile. 

However there were some minor issues that needs to be addressed. In particular the copy paste mode.

There are two behavior being rendered when click the clipboard button:
1. When trying to copy the markdown while the on the preview tab, it generates this formatting on Github's markdown preview:
![Screenshot from 2022-04-19 01-14-06](https://user-images.githubusercontent.com/20263031/163845962-ed0b7e93-d40e-4268-9530-6156fb46b8bb.png)

2. When copying the markdown code from the markdown tab it generates this formatting:
![Screenshot from 2022-04-19 01-11-00](https://user-images.githubusercontent.com/20263031/163846046-935dc1aa-51e3-4c85-9394-65747042cd8c.png) 

I know this is a minor issue but hope you can take a look on it.

**Comment by vinesh27** [comment]
I had this issue today, and after a bit, i went to the `Markdown` tab and copied that, and it worked for me

**Comment by mamaoag** [comment]
Issue resolved based on this commit: [0e0266d142a2a966ac5b0d5f0be33e57ddd2c7e8](https://github.com/danielcranney/profileme-dev/commit/0e0266d142a2a966ac5b0d5f0be33e57ddd2c7e8)

**Comment by danielcranney** [comment]
Thanks @vinesh27 and @mamaoag. The commit that @mamaoag tagged will activate the markdown tab when 'copy' is clicked. This should resolve the issue in the short term, though I will look for a more long term fix that does not involve activating the markdown tab.
