### ISSUE TITLE
light/dark mode button needs aria-label

### ISSUE THREAD

**Issue by EmmaDawsonDev** [danielcranney/profileme-dev#28]
When using a screen reader it is only announced that this is a button and not what it does or which state it is in.

<img width="50" alt="image" src="https://user-images.githubusercontent.com/57045550/175108440-69148b21-83bb-459f-bb9d-616d7920dbf2.png">

**Comment by danielcranney** [comment]
Issue resolved by https://github.com/danielcranney/profileme-dev/pull/37.
