### ISSUE TITLE
Menu btn needs aria label

### ISSUE THREAD

**Issue by EmmaDawsonDev** [danielcranney/profileme-dev#29]
This is only announced as button and no context is given to its function. It needs and aria label to explain the function and also an aria-expanded=true/false attribute adding so that screen reader users know if it's open or closed

<img width="35" alt="image" src="https://user-images.githubusercontent.com/57045550/175108769-f69ad4f5-f660-4d66-8087-cb2b6342e930.png">

**Comment by danielcranney** [comment]
This issue has been resolved with https://github.com/danielcranney/profileme-dev/pull/42.
