### ISSUE TITLE
Skill icons with dark theme won't show well in dark mode

### ISSUE THREAD

**Issue by chivongv** [danielcranney/profileme-dev#4]
I have noticed that icons with a dark theme won't show well in dark mode. Look at the screenshot below. You can see that such as Nextjs and Github icons won't show well in dark mode compared to light mode. Notice how Aftereffects and Premerie icons behave in dark mode  too.

**Dark mode**
![Example dark mode](https://user-images.githubusercontent.com/7512705/165898597-e88308c1-bf64-4fa3-869b-a6d31d76c447.png)

**Light mode**
![Example light mode](https://user-images.githubusercontent.com/7512705/165899088-68eb186a-89f4-43bd-918c-69153c31fdf3.png)

**Comment by danielcranney** [comment]
I'll look into this, as the icons should have a dark mode alternative (ie NextJS logo is white, rather than black as it is on light mode).

**Comment by chivongv** [comment]
Cool! Note that this issue appears on markdown files, for instance [Github](https://github.com), and not on [profileme.dev](https://www.profileme.dev). The reason is because you know the user theme mode on **profileme.dev** and can show the icons according to the user theme mode. But how do you show the correct icons in the markdown file on **Github**?

**Comment by danielcranney** [comment]
Thanks @chivongv, this is a good point. I understand GitHub has introduced theme contexts into their markdown so  that different images can be displayed depending on the mode selected. This should make it easier for us to ensure users get an accurate output. I will add it to the issues.
