### ISSUE TITLE
The menu open by default on smaller screens

### ISSUE THREAD

**Issue by Webothdo** [danielcranney/profileme-dev#5]
This might be a feature that you personally like, but I really don't think is a great idea for user experience - especially with first time users
![Opera Snapshot_2022-05-04_145221_www profileme dev](https://user-images.githubusercontent.com/91842079/166696369-6ebe5417-7071-442a-9cbe-9f64044de088.png)

**Comment by mulfranck** [comment]
Yeah, I was completely confused I never realized it was the menu 😅

**Comment by danielcranney** [comment]
@Webothdo @mulfranck I totally agree. I'm going to be working on a landing page soon to improve UX for new users.

**Comment by danielcranney** [comment]
@Webothdo  @mulfranck This issue has been resolved, and as standard the menu will not be open.
An issue does exist, however, if the menu is open when the user refreshes the page (https://github.com/danielcranney/profileme-dev/issues/15)
