### ISSUE TITLE
Add CSS3 Icon under skills

### ISSUE THREAD

**Issue by Jaycarlx** [danielcranney/profileme-dev#52]
There's currently no CSS3 icon under the skills section. It needs to be updated

**Comment by nishchay7pixels** [comment]
Hi @Jaycarlx . I see one under Skills > Frontend. Could you please confirm if that is where you are referring.

**Comment by danielcranney** [comment]
Thanks @nishchay7pixels, I actually checked with this @Jaycarlx and I understand he found the icon after making this post. Thanks both!
