### ISSUE TITLE
Additional skill badge to frontend section

### ISSUE THREAD

**Issue by shreedharhegde99** [danielcranney/profileme-dev#56]
Please add Chakra UI to `FRONTEND` skills badge. Please let me know if there is any way I can contribute to this. Thank you. 😊

**Comment by M4rk3h** [comment]
Can I jump on this thread and request the r lang be added? i'd be happy to give it a go too.

**Comment by danielcranney** [comment]
As of today, Chakra UI has been added [as per this commit](https://github.com/danielcranney/profileme-dev/commit/5853bf5b169444a8194d9bad3654e7f9738e2957)(and two before).
