### ISSUE TITLE
Better to save details entered whether we leave page  or not 

### ISSUE THREAD

**Issue by AravindAkuthota** [danielcranney/profileme-dev#6]
It's better to modify that while entering details regarding this GitHub profile creation it's good enough if it automatically saves onces the details are entered whether we leave the browser page and revisit it.

**Comment by danielcranney** [comment]
This has been resolved by @AdamJAKing in his latest pull request (https://github.com/danielcranney/profileme-dev/pull/11).

User state stored in localStorage now.
