### ISSUE TITLE
Github Readme Activity Graph Broken Link

### ISSUE THREAD

**Issue by bagashiz** [danielcranney/profileme-dev#67]
![Screenshot from 2022-12-07 11-25-10](https://user-images.githubusercontent.com/91827111/206088127-0e598d84-08af-4d76-a9f3-1a4865091458.png)

It seems they changed the deployment domain based on this [commit](https://github.com/Ashutosh00710/github-readme-activity-graph/commit/f99c5d00b31cde1739921309eabde75a667be82a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).
![Screenshot from 2022-12-07 11-23-37](https://user-images.githubusercontent.com/91827111/206087979-723deb76-e3a3-43d2-8349-465571dc7b41.png)

**Comment by danielcranney** [comment]
[Issue fixed with latest commit.](https://github.com/danielcranney/profileme-dev/commit/80162d11904de040df56d799c38d312a69c32c65)
