### ISSUE TITLE
Please add git in the skills

### ISSUE THREAD

**Issue by phanendraguptha** [danielcranney/profileme-dev#72]
I think it would be great if you could add Git as a skill in the CORE category

**Comment by msboffl** [comment]
If no contribute this, please assign this to me

**Comment by danielcranney** [comment]
This issue was resolved [in this commit](https://github.com/danielcranney/profileme-dev/commit/38ea15ee893f747c058596abb424c2849cd82465).

@msboffl Thank you for your offer!
