### ISSUE TITLE
Getting an error. Some stats are not showing up.

### ISSUE THREAD

**Issue by arghanath007** [danielcranney/profileme-dev#75]
I don't know if this is my issue or from github. I tried opening it on different browsers but got the same result. 

![image](https://user-images.githubusercontent.com/54589605/213860925-f7910521-775c-4302-98ec-2a32bafe1b0e.png)
![image](https://user-images.githubusercontent.com/54589605/213860928-f435de1f-482a-4594-adbb-a1d14d61dbbc.png)
I am getting these error in two places. Before today, it was fine. All of the stats and thing we showing up properly. I noticed these today only.

![image](https://user-images.githubusercontent.com/54589605/213860958-ccd0b439-3ef6-4f3a-9127-d691dc347f22.png)
First error is for these one.

![image](https://user-images.githubusercontent.com/54589605/213860972-cebdb37a-a6c7-43cc-a38f-b85227d823f8.png)
This is for the second error.

I should be seeing those above stats but I am getting these errors. Check my profile. If you want to see it yourself.
Thanks for helping in advance.

**Comment by brandon-devs** [comment]
@arghanath007 These stats come from https://github.com/anuraghazra/github-readme-stats and they often get ratelimited since they're so popular. They usually come back online after a day or two.

**Comment by arghanath007** [comment]
Ok got it. So whoever comes to my profile may see those if it get ratelimited? If so anyway to fix it or can't do anything?

**Comment by brandon-devs** [comment]
@arghanath007 You can deploy your own instance of the app. You can do it for free with [Vercel](https://vercel.com/pricing), and it'll never be offline since you'll be the only one sending requests.

**Comment by arghanath007** [comment]
Oh. That would be nice. Any guide or some help to get started? That would be helpful.

**Comment by brandon-devs** [comment]
@arghanath007 Visit [their website](https://vercel.com/new) and click on `Continue with Github`. Follow along with the steps and import [the repo](https://github.com/anuraghazra/github-readme-stats) when you're prompted to.

**Comment by arghanath007** [comment]
Ok Thanks for the help. I will try it out.
