### ISSUE TITLE
Add Vite tech/skill icon

### ISSUE THREAD

**Issue by 0xSilkweave** [danielcranney/profileme-dev#77]
Hey,

It'd be nice to add the Vite icon as a used tech/skill.

`https://vitejs.dev/logo.svg`

Thanks!

**Comment by danielcranney** [comment]
Thanks @0xSilkweave - This issue has been resolved [in this commit](https://github.com/danielcranney/profileme-dev/commit/ebb74c01209d6fbe3c4f6caaf270ff113bef3027).
