### ISSUE TITLE
Add the Render icon

### ISSUE THREAD

**Issue by FREDVUNI** [danielcranney/profileme-dev#82]
It would be great if you added the **render** icon to the **backend and database section**

**Comment by FREDVUNI** [comment]
Fork the repo and clone it locally and make the changes you want and raise a pull request. You don't need anyone to assign you this task

**Comment by qwertyroop** [comment]
Yeah thankyou, i already did that and raised a PR, idk when it's going to
get merged.

**Comment by FREDVUNI** [comment]
you have to wait for it to be reviewed. It might be a while

**Comment by qwertyroop** [comment]
Ok, no problem.

**Comment by FREDVUNI** [comment]
It was added
