### ISSUE TITLE
Markdown not generating properly

### ISSUE THREAD

**Issue by likendev** [danielcranney/profileme-dev#97]
The markdown content did not generate accordingly. It generate hyperlinks instead. Attached screenshot for elaboration:
![image](https://github.com/danielcranney/profileme-dev/assets/15458805/3cfdfb3e-577b-4d76-9dcf-fe5f2b52d677)

**Comment by kas1qqqq** [comment]
Waiting for fix)

**Comment by rps-code** [comment]
Also waiting for a fix for this. Super clean profile generator though. I'll use it once fixed!

**Comment by likendev** [comment]
@danielcranney I have opened a PR #98 to fix this issue
